open:
 thumb_jo_joint: 0
 thumb_MCP_joint: 0
 thumb_DIP_joint: 0
 pris_thumb_jo_joint: 0
 pris_thumb_DIP_joint: 0
 index_MCP_joint: 0
 index_PIP_joint: 0
 index_DIP_joint: 0
 middle_MCP_joint: 0
 middle_PIP_joint: 0
 middle_DIP_joint: 0
 ring_MCP_joint: 0
 ring_PIP_joint: 0
 ring_DIP_joint: 0
 little_MCP_joint: 0
 little_PIP_joint: 0
 little_DIP_joint: 0
 pris_index_joint: 0
 pris_middle_joint: 0
 pris_ring_joint: 0
 pris_little_joint: 0 

close_grasp:
 thumb_jo_joint: 1.03
 thumb_MCP_joint: 0.52354
 thumb_DIP_joint: 0.52354
 pris_thumb_jo_joint: 0.0103
 pris_thumb_DIP_joint: 1.03
 index_MCP_joint: 1.03
 index_PIP_joint: 1.03
 index_DIP_joint: 1.03
 middle_MCP_joint: 1.03
 middle_PIP_joint: 1.03
 middle_DIP_joint: 1.03
 ring_MCP_joint: 1.03
 ring_PIP_joint: 1.03
 ring_DIP_joint: 1.03
 little_MCP_joint: 1.03  
 little_PIP_joint: 1.03
 little_DIP_joint: 1.03
 pris_index_joint: 0.0103
 pris_middle_joint: 0.0103
 pris_ring_joint: 0.0103
 pris_little_joint: 0.0103

point:
 thumb_jo_joint: 1.03
 thumb_MCP_joint: 0.52354
 thumb_DIP_joint: 0.52354
 pris_thumb_jo_joint: 0.0103
 pris_thumb_DIP_joint: 1.03
 index_MCP_joint: 0
 index_PIP_joint: 0
 index_DIP_joint: 0
 middle_MCP_joint: 1.03
 middle_PIP_joint: 1.03
 middle_DIP_joint: 1.03
 ring_MCP_joint: 1.03
 ring_PIP_joint: 1.03
 ring_DIP_joint: 1.03
 little_MCP_joint: 1.03
 little_PIP_joint: 1.03
 little_DIP_joint: 1.03
 pris_index_joint: 0
 pris_middle_joint: 0.0103
 pris_ring_joint: 0.0103
 pris_little_joint: 0.0103

phone:
 thumb_jo_joint: 0
 thumb_MCP_joint: 0
 thumb_DIP_joint: 0
 pris_thumb_jo_joint: 0
 pris_thumb_DIP_joint: 0
 index_MCP_joint: 1.03
 index_PIP_joint: 1.03
 index_DIP_joint: 1.03  
 middle_MCP_joint: 1.03
 middle_PIP_joint: 1.03
 middle_DIP_joint: 1.03
 ring_MCP_joint: 1.03
 ring_PIP_joint: 1.03
 ring_DIP_joint: 1.03
 little_MCP_joint: 0
 little_PIP_joint: 0
 little_DIP_joint: 0
 pris_index_joint: 0.0103
 pris_middle_joint: 0.0103
 pris_ring_joint: 0.0103
 pris_little_joint: 0

three_grasp:
 thumb_jo_joint: 1.03
 thumb_MCP_joint: 0.52354
 thumb_DIP_joint: 0.52354
 pris_thumb_jo_joint: 0.0103
 pris_thumb_DIP_joint: 1.03
 index_MCP_joint: 1.03
 index_PIP_joint: 1.03
 index_DIP_joint: 1.03
 middle_MCP_joint: 1.03
 middle_PIP_joint: 1.03
 middle_DIP_joint: 1.03
 ring_MCP_joint: 0
 ring_PIP_joint: 0
 ring_DIP_joint: 0 
 little_MCP_joint: 0
 little_PIP_joint: 0
 little_DIP_joint: 0
 pris_index_joint: 0.0103
 pris_middle_joint: 0.0103
 pris_ring_joint: 0
 pris_little_joint: 0

pinch_grasp:
 thumb_jo_joint: 1.03
 thumb_MCP_joint: 0.52354
 thumb_DIP_joint: 0.52354
 pris_thumb_jo_joint: 0.0103
 pris_thumb_DIP_joint: 1.03
 index_MCP_joint: 1.03
 index_PIP_joint: 1.03
 index_DIP_joint: 1.03
 middle_MCP_joint: 0
 middle_PIP_joint: 0
 middle_DIP_joint: 0
 ring_MCP_joint: 0
 ring_PIP_joint: 0
 ring_DIP_joint: 0
 little_MCP_joint: 0
 little_PIP_joint: 0
 little_DIP_joint: 0
 pris_index_joint: 0.0103
 pris_middle_joint: 0
 pris_ring_joint: 0
 pris_little_joint: 0

rock:
 thumb_jo_joint: 0
 thumb_MCP_joint: 0
 thumb_DIP_joint: 0
 pris_thumb_jo_joint: 0
 pris_thumb_DIP_joint: 0
 index_MCP_joint: 0
 index_PIP_joint: 0
 index_DIP_joint: 0
 middle_MCP_joint: 1.03
 middle_PIP_joint: 1.03
 middle_DIP_joint: 1.03
 ring_MCP_joint: 1.03
 ring_PIP_joint: 1.03
 ring_DIP_joint: 1.03
 little_MCP_joint: 0
 little_PIP_joint: 0
 little_DIP_joint: 0
 pris_index_joint: 0 
 pris_middle_joint: 0.0103
 pris_ring_joint: 0.0103
 pris_little_joint: 0
 
scissors:
 thumb_jo_joint: 1.03
 thumb_MCP_joint: 0.52354
 thumb_DIP_joint: 0.52354
 pris_thumb_jo_joint: 0.0103
 pris_thumb_DIP_joint: 1.03
 index_MCP_joint: 0
 index_PIP_joint: 0
 index_DIP_joint: 0
 middle_MCP_joint: 0  
 middle_PIP_joint: 0
 middle_DIP_joint: 0
 ring_MCP_joint: 1.03
 ring_PIP_joint: 1.03
 ring_DIP_joint: 1.03
 little_MCP_joint: 1.03
 little_PIP_joint: 1.03
 little_DIP_joint: 1.03
 pris_index_joint: 0
 pris_middle_joint: 0
 pris_ring_joint: 0.0103
 pris_little_joint: 0.0103
